//
//#define OTHER_TEST
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Common;
using System.Data.SqlClient;
using System.Diagnostics;
using System.IO;
using System.Reflection;
using NSMisc;

namespace NSCs_codegen {
    public partial class cs_codegenDriver {
        const string TRACER_NAME = "blah";

        [STAThread()]
        public static void Main(string[] args) {
            CodeGenArgs args2 = CodeGenArgs.parseArgs(args);
            TextWriterTraceListener twtl = null;
            string logFile, dir, appName, connStr;
            int exitCode = 0;

            args2.setProvider("System.Data.SqlClient");
            //args2.setProvider("NSMyProvider");

            appName = Assembly.GetEntryAssembly().GetName().Name;
#if TRACE
            logFile = Environment.ExpandEnvironmentVariables("%TEMP%" + "\\" + appName + "\\" + appName + ".log");
            if (!Directory.Exists(dir = Path.GetDirectoryName(logFile)))
                Directory.CreateDirectory(dir);

            twtl = new TextWriterTraceListener(logFile, TRACER_NAME);
            Trace.Listeners.Add(twtl);
#endif
            Trace.WriteLine(appName + " starts");

            if (string.IsNullOrEmpty(args2.database)) {
                Console.Error.WriteLine("database not specified.  Cannot continue.");
                args2.showHelp = true;
            }
            if (string.IsNullOrEmpty(args2.outDir)) {
                Console.Error.WriteLine("output-directory not specified.  Cannot continue.");
                args2.showHelp = true;
            }
            if (args2.showHelp) {
                Console.Error.WriteLine("show help here");
                exitCode = 2;
            } else {
                SqlConnectionStringBuilder sb;

                sb = new SqlConnectionStringBuilder();
                sb.ApplicationName = appName;
                sb.DataSource = args2.server;
                sb.InitialCatalog = args2.database;
#if false
            sb.IntegratedSecurity = false;
            sb.UserID = "operator";
            sb.Password = "operator";
#else
                sb.IntegratedSecurity = true;
#endif
                connStr = sb.ConnectionString;

                Trace.WriteLine("ConnectionString is " + (connStr = sb.ConnectionString));

                Trace.WriteLine("Generate files in: " + args2.outDir);
                try {
                    if (!Directory.Exists(args2.outDir))
                        Directory.CreateDirectory(args2.outDir);
                    using (SqlConnection conn = new SqlConnection(connStr)) {
                        conn.InfoMessage += Conn_InfoMessage;
                        conn.Open();
                        Trace.WriteLine(appName + " starts");
                        extractDataFor(args2);
                        Trace.WriteLine(appName + " ends");
                    }
                } catch (Exception ex) {
                    Logger.log(MethodBase.GetCurrentMethod(), ex);
                } finally {

                }
#if TRACE
                Trace.Flush();
                if (twtl != null)
                    Trace.Listeners.Remove(TRACER_NAME);
#endif
                Environment.Exit(exitCode);
            }
        }

        static void Conn_InfoMessage(Object sender, SqlInfoMessageEventArgs e) {
            throw new NotImplementedException();
        }

        //    }

        static void extractDataFor(CodeGenArgs args2) {
            try {
                extractTablesAsClasses(args2);
            } catch (Exception ex) {
                Logger.log(MethodBase.GetCurrentMethod(), ex);
            }
        }

        static void blah() {
            DataTable dt = DbProviderFactories.GetFactoryClasses();

            for (int nrow = 0; nrow < dt.Rows.Count; nrow++) {
                for (int ncol = 0; ncol < dt.Columns.Count; ncol++)
                    Debug.Print(dt.Columns[ncol].Caption + " = " + dt.Rows[nrow][ncol].ToString());
                Debug.Print(string.Empty);
            }
        }

        // This example assumes a reference to System.Data.Common.
        static DataTable findProviderFactoryClasses() {
            // Retrieve the installed providers and factories.
            DataTable table = DbProviderFactories.GetFactoryClasses();

            // Display each row and column value.
            foreach (DataRow row in table.Rows) {
                foreach (DataColumn column in table.Columns) {
                    Console.WriteLine(row[column]);
                }
                Console.WriteLine();
            }
            return table;
        }

        static void extractTablesAsClasses(CodeGenArgs args2) {
            string connStr, appName = Assembly.GetEntryAssembly().GetName().Name;
            DbProviderFactory factory = args2.providerFactory;

            DbConnectionStringBuilder sb = args2.providerFactory.CreateConnectionStringBuilder();

            if (factory is System.Data.SqlClient.SqlClientFactory) {
                ((System.Data.SqlClient.SqlConnectionStringBuilder) sb).ApplicationName = appName;
                ((System.Data.SqlClient.SqlConnectionStringBuilder) sb).DataSource = args2.server;
                ((System.Data.SqlClient.SqlConnectionStringBuilder) sb).InitialCatalog = args2.database;
                ((System.Data.SqlClient.SqlConnectionStringBuilder) sb).IntegratedSecurity = true;
            }

            connStr = sb.ConnectionString;
            Trace.WriteLine("ConnectionString is " + (connStr = sb.ConnectionString));
            try {
                using (DbConnection conn = factory.CreateConnection()) {
                    conn.ConnectionString = connStr;
                    if (conn is SqlConnection)
                        ((SqlConnection) conn).InfoMessage += infoMessageHandler; ;
                    conn.Open();
                    generateCodeFromTables(conn, args2);
                    conn.Close();
                }
            } catch (Exception ex) {
                Trace.WriteLine(ex.Message);
            } finally {

            }
        }

        static void generateCodeFromViews(SqlConnection conn, CodeGenArgs args) {
            generateCodeSysObjectType(conn, args, "V");
        }
        static void infoMessageHandler(object sender, System.Data.SqlClient.SqlInfoMessageEventArgs e) {
            Logger.log(MethodBase.GetCurrentMethod(), e.Message);
        }

        static void generateCodeFromViews(DbConnection conn, CodeGenArgs args) {
            generateCodeSysObjectType(conn, args, "V");
        }

        static void generateCodeFromTables(DbConnection conn, CodeGenArgs args) {
            generateCodeSysObjectType(conn, args, "U");
        }

        static void generateCodeSysObjectType(DbConnection conn, CodeGenArgs args, string objType) {
            List<string> names = new List<string>();
            DbDataReader reader;
            DbProviderFactory factory = args.providerFactory;

            try {
                if (conn.State != ConnectionState.Open)
                    conn.Open();
                using (DbCommand cmd = factory.CreateCommand()) {
                    cmd.Connection = conn;
                    cmd.CommandText = "select name from sysobjects where type='" + objType + "' and uid=user_id('DBO') order by name";
                    reader = cmd.ExecuteReader();
                    while (reader.Read())
                        names.Add(reader.GetString(0));
                    reader.Close();
                }
                foreach (string aTable in names)
                    generateCodeForSingleTable(conn, aTable, args);
                conn.Close();
            } catch (Exception ex) {
                Logger.log(MethodBase.GetCurrentMethod(), ex);
            }
        }

        static void generateCodeForSingleTable(DbConnection conn, string aTable, CodeGenArgs args) {
            DbDataReader reader;

            using (DbCommand cmd = args.providerFactory.CreateCommand()) {
                cmd.Connection = conn;
                cmd.CommandText = "SELECT * FROM " + aTable + " WHERE 1=0";
                cmd.CommandType = CommandType.Text;
                if (conn.State != ConnectionState.Open)
                    conn.Open();
                generateStuff(makeClassName(aTable), args, reader = cmd.ExecuteReader(), aTable);
                reader.Close();
            }
        }
    }
}